version: '3'

services:
  db:
    image: postgres
    volumes:
      - .:/code2/data/
    env_file:
      - .env
  webservice:
    build: .
    volumes:
      - .:/code2/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db